export const LOGIN_ROUTE = "/"
export const NEW_PASS_ENTER_ROUTE = "projectFriday/new-password-enter"
export const PASS_RECOVERY_ROUTE = "projectFriday/password-recovery"
export const PROFILE_ROUTE = "projectFriday/profile"
export const REGISTRATION_ROUTE = "projectFriday/registration"
export const TEST_PAGE_ROUTE = "projectFriday/test"
export const NOT_FOUND_ROUTE = "projectFriday/not-found"